Fix datapack loading for 1.19
iPortalTeam/ImmersivePortalsModForForge pull request #152
Opened 2023-12-18 13:53 UTC by ArgenNova

While the first commit edits cross platform code, there is a Forge specific issue requiring it to be changed.

The second commit adds in the event listeners required for the conventional_dimension_change trigger.

2024-01-10 07:52 UTC, Nick1st requested changes
Thanks for your contribution. I'll have a more detailed look at it later.

2024-01-10 07:52 UTC, Nick1st commented on imm_ptl_core/src/main/java/qouteall/imm_ptl/core/portal/custom_portal_gen/CustomPortalGeneration.java
> +        ResourceKey.createRegistryKey(new ResourceLocation("custom_portal_generation")); // Custom registry namespaces not enabled in forge
Can you please change the comment to
`// FORGE: Custom registry namespaces not enabled in forge`. Makes it easier to search for it when updating.

2024-01-10 07:57 UTC, ArgenNova commented
Changes made

2024-02-09 13:52 UTC, Nick1st commented
Okay, looking good. Sorry for the wait, needed to get some personal things sorted... Will build a new release now!

2024-02-09 13:52 UTC, Nick1st approved these changes

2024-02-09 14:47 UTC, merged